### PR TITLE
Fix issues around post-ban spamming

### PR DESCRIPTION
**Pull request by jpaddison3**
Already reviewed here: https://github.com/centre-for-effective-altruism/EAForum/pull/189

---

Issue 1: If you get banned you can still login

The proximate cause of the error is that express-session keeps you logged in. We remove your loginToken when you get banned, which would log you out, but now express session also has a cookie-based method to keep you logged in. Turns out we don't need to ask passport to use express-session to track logins, so I've removed it. It was silly to have the duplication. Upon doing so, I've removed the code that showed people the banned notice if they're logged in while being banned.

To restate / clarify:

Previously the state would be:

DB:
user.services.resume.loginTokens: 'asdf'
sessions.something: 'zxvc'
Client cookies:
loginToken: 'hjkl'
connect.sid: 'nmop'
Now we only have the loginToken ones.

Issue 2: Even if somehow logged-in, I claim that banned users should not be able to post

Fundamentally, I claim this issue should be guarded against at the permissions level.

Only members can post. Why are banned users members anyway? We can change that!

Issue 3: When testing that banned users who were logged in couldn't comment, I got a very unhelpful error message

Kinda hackily fixed. We should dig into our graphql error handling and fix it all, but right now I'm just assuming that the initial structure was important and only modifying it a little.

Issue 4: The banned notice page was a little sad

Now it is slightly less sad.

### CODE REVIEW

**Comment by jpaddison3** [comment]
Deepscan appears fake

**Comment by darkruby501** [comment]
I'm excited for this PR as I've failed to get around to merging your hotfix and everyday ganga123 plagues us.

**Comment by jpaddison3** [comment]
It's already been reviewed, you could just merge it

**Comment by darkruby501** [comment]
Alright, I'm trusting you. ;)

**Comment by darkruby501** [comment]
This didn't work and we've continued to have a daily spam poster.

**Pull request merged**
