### PR TITLE
Restore autolinking without rendering user input

### PR DESCRIPTION
**Pull request by jpaddison3**

### CODE REVIEW

**Comment by Discordius** [comment]
Alas, you will have to merge with the latest devel again, because we had a change in the dependency of our cronjob library that breaks tests if you are behind.

**Comment by jpaddison3** [comment]
@Discordius

**Comment by jimrandomh** [comment]
If there's any XSS left, it's subtle enough that I can't find it this time around.

**Comment by jpaddison3** [comment]
Do you think there should be more paranoia? I feel like I want more practice on security mindset.

**Comment by jpaddison3** [comment]
Oh, that comment was written before the merge happened. Then I read Bruce Schneier and EY on the topic.

**Comment by Discordius** [comment]
Lol. 

I think paranoia is good, but in this case I think there aren't that many attack vectors left. I thought for 10 minutes about it, and couldn't see any way of doing XSS with the current setup, which I guess isn't really security mindset, but seems good enough given other areas that are more likely to allow for vulnerabilities.

Importantly, we do have enough bandwidth to just supervise all new content, so we would notice quite quickly if anyone was abusing some kind of XSS. Which shields against the worst-case outcomes (though that outcome is still quite bad).

**Pull request merged**
