### PR TITLE
Fix all the causes of various problems with Firefox Mobile

### PR DESCRIPTION
**Pull request by Discordius**
The bugs with CKEditor went away when I upgraded the CKEditor version, which I wanted to do anyways. 

The second-biggest change and likely the most risky change in this PR is an upgrade of the `@babel/runtime` version, since the version we had pinned was causing crashes on Firefox mobile. Presumably we pinned that reason for a good reason, so we should check that we didn't introduce a separate error with the version upgrade.

┆Issue is synchronized with this [Trello card](https://trello.com/c/45Cus7o7) by [Unito](https://www.unito.io/learn-more)

### CODE REVIEW

**Comment by jimrandomh** [comment]
The commit message when we pinned the exact babel version was

> Upgrade and pin exact babel version
>
> Possibly fixes TravisCI issue with mismatched babel runtime.

Given that Travis seems to be working fine, I think the issue has been resolved upstream.

**Comment by jimrandomh** [comment]
Tested on Firefox Mobile on a `npm run start-prod-db`. The original crash (`Watchdog is not a constructor`) is resolved, but it's still crashing; I get a correct-looking but unfocusable comment box, and this in the console:

```
TypeError: "n is not iterable"
    node_modules lesswrong/lesswrong-editor/build/ckeditor.js:20
    node_modules lesswrong/lesswrong-editor/build/ckeditor.js:20
    node_modules lesswrong/lesswrong-editor/build/ckeditor.js:22
    node_modules lesswrong/lesswrong-editor/build/ckeditor.js:22
    node_modules lesswrong/lesswrong-editor/build/ckeditor.js:22
    node_modules lesswrong/lesswrong-editor/build/ckeditor.js:22
    _initializeEditor /node_modules/meteor/lesswrong/components/editor/ReactCKEditor.tsx:125
    node_modules lesswrong/lesswrong-editor/build/ckeditor.js:22
    bindEnvironment http://192.168.30.179:3000/packages/meteor.js?hash=857dafb4b9dff17e29ed8498a22ea5b1a3d6b41d:1234
modules.js:163895:46
TypeError: t is undefined
```

**Comment by jimrandomh** [comment]
I think this fix PR is definitely fixing things, and is unlikely to be introducing any new issues; this is probably a case of there being multiple issues, and not having gotten all of them. Possibly the last issue is somehow specific to my testing setup.

So it makes sense to merge your fix PR to devel, since it is at least progress, and see if it still reproduces on lessestwrong.

**Comment by Discordius** [comment]
Oh, I have a guess. Can you run `yarn add ./public/lesswrong-editor` and check whether the issue is still not fixed afterwards? 

The thing that fixed the iterable issue was a CKEditor upgrade, which doesn't propagate through our package system naturally (which is itself annoying). So unless you explicitly re-added the lesswrong-editor package, you should still get the iterable error.

**Pull request merged**
