### PR TITLE
remove small-upvote weight 3

### PR DESCRIPTION
**Pull request by Raemon**

### CODE REVIEW

**Comment by jpaddison3** [comment]
Won't the thing that happens be:
 1. Someone small-3 upvotes a comment – karma: 1->4
 2. This get's implemented – karma: 4->4
 3. Someone else small-1 upvotes that comment – karma: 4->4

Where the last step someone thinks their upvote didn't work. This is because it recalculates every time. Maybe it stores the weight of the historical vote so it's fine?

**Comment by Raemon** [comment]
If I understand you correctly, you're pointing to the fact that votes that previously had a "small-vote-weight-3" will behave a bit wonkily when other people vote on them?

That seems true, but not much weirder than other situations where people vote on a thing, and they find that someone else has recently voted on that thing, such that they don't see the new karma that they expected.

(Ideally we actually get around to re-running vote totals, which I assume would get rid of the past discrepancies)

**Comment by jpaddison3** [comment]
Correct.

**Comment by jpaddison3** [comment]
But I think this will happen a lot more than normal, because there will be so many people with that vote. It also might be easily mitigated with a recalculate meteor shell command.

**Comment by Raemon** [comment]
It's plausible we want to actually have the re-run-votes function ready before we merge this

**Comment by Raemon** [comment]
(but also note, this is a smaller change than when we implemented strong-and-weak upvotes, where many people's effective default vote weight was dramatically reduced. I don't think we did anything special for that)

Also actually I think there won't be a (perceived) issue here – I think the old vote weights will only re-update when the original author votes on them, not newcomers.

**Pull request merged**
