### PR TITLE
[NEEDS REVIEW] Ungate pingbacks

### PR DESCRIPTION
**Pull request by jimrandomh**
Everything's merged. We should rerun the `generatePingbacks` migration to make pingbacks for all the newish routes, then we can ungate this.

### CODE REVIEW

**Comment by zackmdavis** [comment]
pingbacks are the best feature :sparkling_heart:

**Comment by Discordius** [comment]
Only last blocker I can think of is truncating the post titles properly. Other than that, it seems good.

**Comment by jimrandomh** [comment]
Meta: Remember to unassign yourself when you review something. I use GitHub PRs to keep track of what I have in-flight, in a way that doesn't incorporate ephemeral conversations.

**Comment by Discordius** [comment]
Note for posterity: Approved with all the bug fixes, but despite the name, not actually ungating the pingbacks.

**Pull request merged**
