### PR TITLE
Conditionally load events components

### PR DESCRIPTION
**Pull request by jpaddison3**
Recent changes added event components that were loaded off of the Components object, even on non-event routes. This caused errors on the EA Forum and anyone using `"hasEvents": false`, as those components were never defined.

Introduce utility function for conditionally loading.

### CODE REVIEW

**Comment by jpaddison3** [comment]
Please hold

**Comment by jpaddison3** [comment]
Fixed

**Comment by jimrandomh** [comment]
So, what happens is, components get loaded when you destructure or dereference them out of `Components`. (This is done with proxy magic in `vulcan-lib/lib/modules/components.js`, and is a recent thing.) What happens is, `packages/lesswrong/lib/components.js` specifies a mapping from a component name to which file you need to import to get that component; then when you say `Components.Foo`, it checks its cache and imports that file if necessary.

If you try to get a component that doesn't exist, it will crash. (In earlier versions, it would instead silently give you `null`, when you expected a component, which made for more difficult debugging). There are two places where that happens: at the top of render functions, where we have lines like
```
const { Foo } = Components
```
and in the middle of trees, where we have lines like
```
{showFoo && <Components.Foo myProp="..."/>}
```
There's an important difference between these, which is that the first version always tries to load the `Foo` component, while the second version only tries to load it if `showFoo` is true. We usually use the former version as a notational convenience (because everything starting with `Components.` is harder to read).

...The practical upshot of all of which is, `loadEventComponent` probably isn't necessary. Though it might still be handy as a way of indicating *why* some components are loaded in a special way

**Comment by jpaddison3** [comment]
Makes sense. Currently I think Components.Event* is nicer than the unpleasant-feeling utility function. Will close and resubmit.

**Pull request closed without merging**
