### PR TITLE
lwTertiary is green

### PR DESCRIPTION
**Pull request by Raemon**

### CODE REVIEW

**Comment by Raemon** [comment]
image

**Comment by Raemon** [comment]
My current thoughts:

It seems important for the tertiary buttons to actually be fairly muted. This is incompatible with that color also being useful for highlighting links (since it's not distinct enough from black text). I think we'll just need an extra color for links.

Here's a potential green/blue distinction between unread and unread links. My main worry with using blue (or any non-green color) for links is that as you read links, the site will generally shift from being "mostly green" to 
mostly blue". I think this is a problem mostly because we don't _otherwise_ have branding colors, so while you're in the middle of a post it'll just change the feel of the site a lot. 

image

I feel pretty comfortable punting this problem to the future. If we don't come up with a way to keep our brand-feel with changing-link-colors, I think we can either a) come up with a non-color way to do it (bolding, underlining, etc), b) just leave links green and don't distinguish between read and unread (it's not like people are complaining about that right now) or... c) just decide to formally sacrifice that aspect of the branding.

**Comment by jimrandomh** [comment]
Something about this particular shade of green is offputting to me.

**Comment by Raemon** [comment]
Yeah I'm actually noticing that too. Feels a bit too sickly green

**Comment by Raemon** [comment]
Here's a version that's sort of abandoning the attempt at a two color system (this is technically a different color of green but don't expect anyone to notice). But I think I might have come around to "actually, having 'big block of green in an icon or something' is an okay way to distinguish new content from random buttons."

image

**Comment by Raemon** [comment]
Very slightly more muted version

image

**Pull request merged**
