### PR TITLE
Auto-sign and date mod comments

### PR DESCRIPTION
**Pull request by Raemon**
(actually created by Jacob, I just wanted the PR to make it easier to check the diff)

### CODE REVIEW

**Comment by lagerros** [comment]
Whenever you look at a user in the sunshine sidebar, this adds your name and date, like this: 
image

(One might debate whether it should only be added when you actually add some new text. This way is easier to build, and it might just be a feature rather than a bug. Might also form the basis for a richer mod-activity log, if one added some automated notes when an action like snooze/flag was taken.)

**Comment by Raemon** [comment]
Oh I quite like the ‘note when a mod snoozes or bans or whatever a user’

**Comment by lagerros** [comment]
(Note don't merge this, am working on an update and discussed with Oli)

*All the best,*
Jacob Lagerros

Sent via Superhuman ***@***.***>

**Comment by lagerros** [comment]
Okay, this now ready to be merged

**Comment by Raemon** [comment]
Note the deepscan error issue. (Click on the "details" section of the Deepscan section)

**Comment by lagerros** [comment]
Checked it out; seems fine. (It's a residual unused argument that might be
used for positioning the caret later)

*All the best,*
Jacob Lagerros

Sent via Superhuman ***@***.***>

**Review by lagerros — APPROVED** [review]

**Pull request merged**
