### PR TITLE
Assorted indexing-related fixes

### PR DESCRIPTION
**Pull request by jimrandomh**

### CODE REVIEW

**Comment by Raemon** [comment]
Does this need to be added to both the default and commentReplies views? Seems like adding it to default should automatically add it to commentReplies?

**Comment by jimrandomh** [comment]
The change to `commentReplies` is a change, not an addition. I don't think it's likely to matter for performance, but there may be some corner cases where it fixes the semantics.

**Comment by jimrandomh** [comment]
Added second commit which moves `deleted` and `deletedPublic` from the index prefix to the index suffix, making the indexes actually-usable.

**Comment by jimrandomh** [comment]
Fixes #1504

**Pull request merged**
