### PR TITLE
[WIP] Misc Vulcan cleanup

### PR DESCRIPTION
**Pull request by jimrandomh**
A bunch of small things to cut down the amount of Vulcan code and speed up bundle initialization.

### CODE REVIEW

**Comment by Discordius** [comment]
The timezone handling is indeed still active and used, so I am confused why you are removing it. 

This broke all of daily, past events, future events and probably at least two or three other places.

**Comment by jimrandomh** [comment]
The timezone handling is unused. The `timeField` handling on the other hand was still used, so I'll put it back in.

**Comment by Discordius** [comment]
Not fully sure what you mean by the timezone handling. It's the only place where we handle the `before` and `after` parameters on post queries, so at least that stuff needs to stay in place, and then you need to do at least some timezone handling to deal with that.

**Comment by jimrandomh** [comment]
It looks like `posts/parameters.js` is sitting on top of a pile of mostly-cancelling errors. (Not fully cancelling--bad stuff will happen when you have a server-client timezone mismatch which crosses a day boundary.) In particular, what's happening is:

 * The daily-list components and associated utility functions compute time ranges correctly, using the right time zone
 * They then truncate off the time, leaving only the date, and put that into `terms`
 * `posts/parameters.js` then applies its own timezone handling, rounding off to the day again, rounding up for after and down for before. If you're lucky, this cancels out the truncation that just happened. But you might also end up off by a day.

This particular hack is the last thing using `Inject`, so it's also anchoring a significant amount of code. Unfortunately, some of the commits in this PR are only valid under the assumption that that could be removed.

**Pull request closed without merging**
