### PR TITLE
Even out spacing in Header

### PR DESCRIPTION
**Pull request by jpaddison3**
And prevent shifting around on search icon appearing after SSR. (This can cause usernames to wrap differently.)

### CODE REVIEW

**Comment by jpaddison3** [comment]
(Hold on, about to work on fixing the vertical alignment of search and karma as well)
image

**Comment by jpaddison3** [comment]
(Done)

**Comment by jpaddison3** [comment]
This is stuck on me not being able to see the deepscan error

**Comment by Discordius** [comment]
The deepscan error is fake

**Comment by jpaddison3** [comment]
Flaky test

**Pull request merged**
