### PR TITLE
Add Page-Level trackers (depends on #2760)

### PR DESCRIPTION
**Pull request by darkruby501**
**this PR depends on PR #2760: addInViewTracking**

This PR introduces analytics code to generate events for:

1) user inactivity/idleness, 2) page-visibility (i.e. visible tab), 3) a timer which only counts up while page is visible and user is active, 4) an event when user is leaving the page (onBeforeUnload).

Longer dsecription:
- when the pageVisibility API changes the page between different states: hidden/visible/pre-render/unloading (mostly the first two)
- activityDetection: uses mouse and keyboard events and implements a timeout which generates "inactive/active" events
- when beforeUnload fires which happens before refresh or upon navigate to another page
- a timer which counts up and sends events every N seconds so long as the pageIsVisible && !userIsIdle

### CODE REVIEW

**Comment by darkruby501** [comment]
The Deepscan issue seems fine? The "element" value is null-checked and registers a console.log error if it isn't. If it's missing, program should fail on Line 29 which it refers to?

**Comment by jimrandomh** [comment]
When making PRs based on other PRs, best practice is to (1) put the commit ID of the first commit that's specific to this PR, in the description; and (2) avoid merging commits, rebasing instead. That way, in GitHub I can select a range of commits and review only the parts that are new.

**Comment by darkruby501** [comment]
> When making PRs based on other PRs, best practice is to (1) put the commit ID of the first commit that's specific to this PR, in the description; and (2) avoid merging commits, rebasing instead. That way, in GitHub I can select a range of commits and review only the parts that are new.

@jimrandomh Ah, neat. Makes complete sense. I'll do that in the future. Sorry for not doing it this time.

A couple of questions:
1) when fixing things on PRs based on other PRs, where should I be making those fixes?
2) Why don't we generally rebase?

**Comment by jimrandomh** [comment]
PRs-based-on-PRs are a thing we only do rarely, because they're kind of a mess when you try to review them. I think making one merged PR would've been significantly better, in this case.

**Comment by jimrandomh** [comment]
This PR is a subset of https://github.com/LessWrong2/Lesswrong2/pull/2764 , closing to reduce confusion.

**Pull request closed without merging**
