### PR TITLE
Logged out comment boxes

### PR DESCRIPTION
**Pull request by jimrandomh**
Requires matching Vulcan PR: https://github.com/LessWrong2/Vulcan/pull/70 .

This makes it so that comment/answer boxes and Reply buttons appear to logged out users. If they click Submit, then a flash message appears which says "Log in to submit your comment." or "Log in to submit your answer.".

When they do log in, unfortunately, they will lose up to 29 characters of their comment due to slightly-broken autosave (#1730). This is the same issue as when refreshing or closing the tab and coming back, but much more noticeable and problematic in this context.

Tested by trying to post an answer, a top-level comment, and a reply, as a logged out user, and again as a logged-in user.

### CODE REVIEW

**Comment by jimrandomh** [comment]
TODO: Customize the message for Alignment Forum.

**Comment by Discordius** [comment]
You will want to update the test that's failing

**Comment by jimrandomh** [comment]
Merged, but merge conflicts were unusually substantive. Needs to be fully retested.

**Comment by jimrandomh** [comment]
Retested, catching and fixing one merge-created crash bug (the New Comment tab on the Questions page). Seems good now.

**Pull request merged**
