### PR TITLE
CKEditor LaTeX Quality of Life Improvements

### PR DESCRIPTION
**Pull request by Discordius**
On Scott Garrabrants request, three features for the new LaTeX plugin for CKEditor: 

1.  Allow you to convert selected text into LaTeX when you open the LaTeX menu
1.  Allow you to leave the LaTeX dialog via pressing Tab
1.  When you leave the LaTeX dialog, place the selection right after the element, not on the element, allowing you to continue writing without having to press the right-key

┆Issue is synchronized with this [Trello card](https://trello.com/c/zUzVdpIa) by [Unito](https://www.unito.io/learn-more)

### CODE REVIEW

**Comment by Discordius** [comment]
The latest commit also fixes a weird bug where sometimes LaTeX elements that are at the end of a paragraph can make your life horrible and randomly delete tons of content for no apparent reasonn.

**Comment by jimrandomh** [comment]
Playing around with this, I ran into a weird bug where LaTeX blocks sometimes get converted to plain text. Try this key sequence in an empty post:

```
<Cmd+4>\LaTeX<enter><space><Cmd+4>\LaTeX<enter><space>
```

The last <space> causes both LaTeX blocks to transform from LaTeX to plain text.

**Comment by Discordius** [comment]
Reverted the changes. I think this should now be ready to merge (there are still some obscure bugs with LaTeX but they are already there and it's kind of hard to run into them).

**Comment by jimrandomh** [comment]
The bug still replicates for me

**Comment by Discordius** [comment]
Did you run `yarn add ./public/lesswrong-editor/`? Since it doesn't replicate for me.

**Comment by Discordius** [comment]
In general, if you don't want to bother reinstalling the stuff every time, you can do quick tests on CKEditor stuff by opening this file in your browser: https://github.com/LessWrong2/Lesswrong2/blob/devel/public/lesswrong-editor/sample/index.html

**Comment by jimrandomh** [comment]
Ok, that fixed it. I was under the impression a `yarn install` was enough to get everything up to date when switching branches; maybe there should be a script for it in `package.json`?

**Comment by Discordius** [comment]
Yeah, let's add a script. Don't see any particular reason not to. Will do it in a new branch.

**Pull request merged**
