### PR TITLE
Filter Mode UI updates

### PR DESCRIPTION
**Pull request by Raemon**
Changes "-/+ infinity" to "Hidden" and "Required", makes them a little greenish, and also changes the "X" to a "Remove Filter" since it was confusing for some users.

image

### CODE REVIEW

**Comment by Discordius** [comment]
I really don't like the remove filter in the bottom right corner. I think it's pretty confusing and feels like it doesn't belong at all to the same UI element.

Not sure whether we can do something better, but I do dislike the current thing quite a bit. 

The rest of the changes seems good to me.

**Comment by Raemon** [comment]
Yeah, I'm not thrilled with it either. Wasn't sure what else to do. Maybe move it back up to the top-right?

**Comment by Discordius** [comment]
Yeah, top right seems better to me.

**Comment by Raemon** [comment]
New version:

image

**Pull request merged**
