### PR TITLE
Revision system

### PR DESCRIPTION
**Pull request by Discordius**

### CODE REVIEW

**Comment by jimrandomh** [comment]
It gets a bit further now than it did before, but saving a new post currently fails with:

```
Uncaught TypeError: Cannot read property 'type' of undefined
    at EditorFormComponent.getCurrentEditorType (EditorFormComponent.jsx:196)
    at EditorFormComponent.render (EditorFormComponent.jsx:238)
    at finishClassComponent (modules.js?hash=840060035da0d2fd37e7b3dc3a3d88e4ce746439:110542)
    at updateClassComponent (modules.js?hash=840060035da0d2fd37e7b3dc3a3d88e4ce746439:110504)
    at beginWork (modules.js?hash=840060035da0d2fd37e7b3dc3a3d88e4ce746439:111173)
    at performUnitOfWork (modules.js?hash=840060035da0d2fd37e7b3dc3a3d88e4ce746439:113212)
    at workLoop (modules.js?hash=840060035da0d2fd37e7b3dc3a3d88e4ce746439:113251)
    at HTMLUnknownElement.callCallback (modules.js?hash=840060035da0d2fd37e7b3dc3a3d88e4ce746439:97448)
    at HTMLUnknownElement.sentryWrapped (modules.js?hash=840060035da0d2fd37e7b3dc3a3d88e4ce746439:177567)
    at Object.invokeGuardedCallbackDev (modules.js?hash=840060035da0d2fd37e7b3dc3a3d88e4ce746439:97486)
```

**Comment by jimrandomh** [comment]
The User Profile page crashes with:

```
modules.js?hash=584d75be7eadeba0a9d3af935a5ff6afb5ec8542:67518 Uncaught (in promise) Error: GraphQL error: Field "moderationGuidelines" of type "Revision" must have a selection of subfields. Did you mean "moderationGuidelines { ... }"?
    at new ApolloError (modules.js?hash=584d75be7eadeba0a9d3af935a5ff6afb5ec8542:67518)
    at modules.js?hash=584d75be7eadeba0a9d3af935a5ff6afb5ec8542:69054
    at meteor.js?hash=0504f43f667698535416b00eb44eb6f53161cb63:1223
```

When I make an edit and click Publish, the post page shows me the old body until I refresh.

After creating a major revision, the PostsRevisionSelector still isn't visible.

Dialect: "You are viewing a version of this post published on the 28th Jan 2019" comes across as overly British; change to "You are viewing a version of this post on published 28 Jan 2019."

**Comment by Discordius** [comment]
Note: This PR also requires a matching merge of this Vulcan PR

https://github.com/LessWrong2/Vulcan/pull/56

**Comment by jimrandomh** [comment]
Problems:
 * Submitting the form on the Edit Profile page crashes with
```
Error: GraphQL error: [{"id":"errors.required","path":"moderationGuidelines.canonicalContent.data","properties":{"collectionName":"Users","typeName":"User","name":"moderationGuidelines.canonicalContent.data","type":"required","value":null}}]
    at new ApolloError (modules.js?hash=584d75be7eadeba0a9d3af935a5ff6afb5ec8542:67518)
    at modules.js?hash=584d75be7eadeba0a9d3af935a5ff6afb5ec8542:68432
    at meteor.js?hash=0504f43f667698535416b00eb44eb6f53161cb63:1223
```

If I select the Markdown editor by editing my user in the database, the Activate Markdown Editor checkbox still isn't checked on the Edit Account page, and this error appears on load:
```
Warning: `value` prop on `textarea` should not be null. Consider using an empty string to clear the component or `undefined` for uncontrolled components.
    in textarea (created by Textarea)
    in div (created by Textarea)
    in Textarea (created by WithStyles(Textarea))
    in WithStyles(Textarea) (created by InputBase)
    in div (created by InputBase)
    in InputBase (created by WithStyles(InputBase))
    in WithStyles(InputBase) (created by Input)
    in Input (created by WithStyles(Input))
    in WithStyles(Input) (created by EditorFormComponent)
    in div (created by EditorFormComponent)
    in div (created by EditorFormComponent)
    in EditorFormComponent (created by WithStyles(EditorFormComponent))
    in WithStyles(EditorFormComponent)
    in WithUserComponent (created by FormComponent)
    in FormComponent (created by FormGroup)
    in div (created by FormGroup)
    in div (created by FormGroup)
    in FormGroup (created by WithStyles(FormGroup))
    in WithStyles(FormGroup) (created by SmartForm)
    in form (created by Formsy)
    in Formsy (created by SmartForm)
    in div (created by SmartForm)
    in SmartForm (created by withLoader(Form))
...
```

With the markdown editor selected, when I submit or edit a comment it appears to work, but I get this error in the console:

```
Warning: `value` prop on `textarea` should not be null. Consider using an empty string to clear the component or `undefined` for uncontrolled components.
    in textarea (created by Textarea)
    in div (created by Textarea)
    in Textarea (created by WithStyles(Textarea))
    in WithStyles(Textarea) (created by InputBase)
    in div (created by InputBase)
    in InputBase (created by WithStyles(InputBase))
    in WithStyles(InputBase) (created by Input)
    in Input (created by WithStyles(Input))
    in WithStyles(Input) (created by EditorFormComponent)
    in div (created by EditorFormComponent)
    in div (created by EditorFormComponent)
    in EditorFormComponent (created by WithStyles(EditorFormComponent))
    in WithStyles(EditorFormComponent)
    in WithUserComponent (created by FormComponent)
    in FormComponent (created by FormGroupComponent)
    in FormGroupComponent (created by SmartForm)
    in form (created by Formsy)
    in Formsy (created by SmartForm)
    in div (created by SmartForm)
    in SmartForm (created by withCreateComment(SmartForm))
    in withCreateComment(SmartForm)
    in FormWrapper (created by withRouter(FormWrapper))
    in withRouter(FormWrapper) (created by withApollo(withRouter(FormWrapper)))
    in withApollo(withRouter(FormWrapper)) (created by withCurrentUser(withApollo(withRouter(FormWrapper))))
    in withCurrentUser(withApollo(withRouter(FormWrapper))) (created by CommentsNewForm)
    in div (created by CommentsNewForm)
    in CommentsNewForm (created by WithStyles(CommentsNewForm))
```

Creating a new sequence from `/sequencesnew`, submitting crashes with
```
Error: GraphQL error: Variable "$data" got invalid value {"userId":"CjoypfuYyawBpMJax","title":"My New Sequence","gridImageId":null,"bannerImageId":null,"undefined":{"canonicalContent":{"type":"draftJS","data":{"blocks":[{"key":"6k16f","text":"Hai.","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}}],"entityMap":{}}},"updateType":"minor"}}.
In field "undefined": Unknown field.
    at new ApolloError (modules.js?hash=584d75be7eadeba0a9d3af935a5ff6afb5ec8542:67518)
    at modules.js?hash=584d75be7eadeba0a9d3af935a5ff6afb5ec8542:68432
    at meteor.js?hash=0504f43f667698535416b00eb44eb6f53161cb63:1223
```

Unsubmitted posts and comments don't get saved (or perhaps don't get restored) with the Markdown editor enabled.

The `wordCount` field on posts doesn't get populated, which causes `PostsItem` to display a funny-looking unstyled `0` instead of saying "N words".

Nitpicks and out-of-scope features:
 * When looking at the newest revision of a post, there isn't any way to navigate to past revisions from the post heading; the only way to get them is by clicking on the notice on old comments.
 * Editing a comment doesn't clear the "Response to previous version" flag from it
 * Comments responding to *future* versions of a post don't have a "Response to future version" flag on them
 * There is no way to see that a comment has been edited or see its past revisions

**Pull request merged**
