### PR TITLE
Lighter and rounder comment borders

### PR DESCRIPTION
**Pull request by Discordius**
┆Issue is synchronized with this [Trello card](https://trello.com/c/8Tut1mAI) by [Unito](https://www.unito.io/learn-more)

### CODE REVIEW

**Comment by Raemon** [comment]
Hmm. I don't think this currently looks better in situations with nested comments, answers, and unread comments (there's a bunch of little finicky things I think need to be gotten right about how the border-radiuses interrelate)

**Comment by Raemon** [comment]
Note: this is what this currently looks like with nested comments, which looks bad to me. I'm actually a bit skeptical you can make it look good. Consider this PR in Oli's court.

image

**Comment by darkruby501** [comment]
Looks fine to me.

**Comment by Raemon** [comment]
If a majority of people straightforwardly prefer the new thing, seems fine. What I would prefer is if the interior comments had less-rounded-corners than the outer ones, and in particular, did not have the right-aligned corners be rounded.

**Comment by Raemon** [comment]
Closing this because it's going to get folded into Frontpage Overhaul

**Pull request closed without merging**
