### PR TITLE
Set up Travis testing and deployment

### PR DESCRIPTION
**Pull request by Discordius**

### CODE REVIEW

**Comment by jimrandomh** [comment]
How are the `.js.enc` files generated? I assume those are encrypted versions of the corresponding `.js` files from the `LessWrong-Credentials` repo? If so, it'd be good to have a script (in either repo) to regenerate them.

**Comment by Discordius** [comment]
Those are generated by some command I have to look up in my command history again. Agree that there should a script somewhere that does it for you.

**Comment by jimrandomh** [comment]
The only thing missing before merging this is some documentation on how to generate the `.js.enc` files.

**Comment by Discordius** [comment]
Done. Though we should probably still only merge this next week or something, since it might break our ability to deploy

**Pull request merged**
