### PR TITLE
Tag Voting For All

### PR DESCRIPTION
**Pull request by Raemon**
Changes the UI of the /tagVoting page to make it more presentable, and lets anyone view the page.

I'm not 100% sure about the performance of the page, and whether I made it worse – on localhost, the page generally takes a very long time to load (even before I added my changes). I don't trust my ability to check locally.

### CODE REVIEW

**Comment by Raemon** [comment]
image

**Comment by darkruby501** [comment]
Looks good. If it's a cheap change, I do think making the hover-over larger (or text smaller) would be a bit good. But I wouldn't do a tonne of work for it.

**Comment by Discordius** [comment]
Pretty sure this won't work because of vote permissions.

**Comment by Discordius** [comment]
And indeed, this is what it looks like for logged-out users: 

image

Fixing this requires some careful thinking since we really want to avoid giving users access to the vote data for other types of votes, and I haven't had great experiences with making field-level permissions be responsive to the actual data.

**Comment by Discordius** [comment]
Happy to pair on it, if it would be useful.

**Pull request merged**
