### PR TITLE
Add indicators for LaTeX horizontal scroll

### PR DESCRIPTION
**Pull request by jimrandomh**
This patch makes it so that if a LaTeX block in a post or comment is wide enough to need a horizontal scrollbar, it gets expanded to a larger touch target and gets an indicator on the left/right sides to show that it's scrollable.

### CODE REVIEW

**Comment by jimrandomh** [comment]
Fixes #1170.

**Comment by jimrandomh** [comment]
There are lots of little bits of polish that could be added to this.

**Comment by jimrandomh** [comment]
We discussed a broader architectural thing which would make it possible to do this (and also link-previews) more elegantly. But it's going to be awhile before I get to that, so, I think it's worth taking this as-is (ugly DOM API usage included) in the mean time.

**Comment by Discordius** [comment]
Yeah, seems fine for now.

**Pull request merged**
