### PR TITLE
This time actually fix the user ban menu bug

### PR DESCRIPTION
**Pull request by Discordius**
I figured out why we made the changes I reverted in #2985! 

It broke users editing posts that admins had edited for some reason before. This actually fixes the underlying bug.

┆Issue is synchronized with this [Trello card](https://trello.com/c/wFXV4cRs) by [Unito](https://www.unito.io/learn-more)

### CODE REVIEW

**Comment by jimrandomh** [comment]
With the `hidden:true` added, does this mean the post author can no longer see a list of banned users, only add users via the ban-menu?

**Comment by Discordius** [comment]
Yeah, though that's planned as a temporary change. Currently no one can access it anyways (as in, we merged a PR that unhid it, and this rehides it again while fixing the underlying bug, and then in a week or so after I checked that it works, we can completely unhide it again).

**Comment by jimrandomh** [comment]
In that case I'm confused as to what the underlying bug is and how this fixes it. It seems to be simplyifying the call to `Users.canModeratePost` by removing a no-op wrapper, and then putting it into an array. If putting it into an array is a bugfix, that seems like a bug in `Users.canCreateField` and/or `Users.canUpdateField`, since those functions are clearly intended to be agnostic as to whether they receive an array or a function.

**Comment by jimrandomh** [comment]
(I notice that `Users.canCreateField` doesn't take a document parameter, which means that a non-admin trying to populate a banlist on a new post before submitting it would fail, in circumstances where populating the same banlist on a draft or published post would succeed.)

**Comment by Discordius** [comment]
Yep, it's a bug in how the arrays get handled. If you pass them a function then the frontend form doesn't seem to respect that and try to submit the fields anyways, which fails on form submission.

Putting it in an array makes everything properly observe the permissions.

**Comment by jimrandomh** [comment]
Made a separate issue for the general case. This workaround for the narrow case seems fine.

**Pull request merged**
