### PR TITLE
Partial Recommendations Rework

### PR DESCRIPTION
**Pull request by Raemon**
This removes some buttons from the Recommendations section:

1. The "Login" button under Core Reading is just gone
2. The "View All Curated" button is replaced by the "Curated Icon" on posts being a link (as well as most such post-item-icons being links)
3. The Subscribe buttons are moved over to the Nav Bar

This also removes the Open Questions Nav Item, which wasn't really pulling it's weight (currently you can get to the /questions page via clicking on the Question icon on PostItems)

image

### CODE REVIEW

**Comment by Discordius** [comment]
I would combine the sidebar subscribe items into "Subscribe (RSS/Email)". They both open the same dialog that allows you to select either, and I don't think it's worth having two menu items for that.

**Comment by Raemon** [comment]
There's a "Chesteron's Width Limit" on TabSubNavigationItem. I'm looking into changing it but want to remember what it's for

image

**Comment by Discordius** [comment]
It's there because it broke out of the hamburger menu when it was too wide on small devices, if I remember correctly.

**Comment by Raemon** [comment]
Oooohhhh wow Chesteron what a good rule you invented.

**Comment by Raemon** [comment]
Bugs/Issues I know about:

– the aforementioned "this makes things break out of small devices". I assume this isn't that hard, but needs more attention than I have right now.

– the alignmentforum icon doesn't successfully link to the alignment forum (current guess is because the broader PostsItem2 has an onClick handler, and unlike the other icons which use <Link/>, the alignment forum one uses <a>, which isn't powerful enough)

– This PR makes some-but-not-all usernames turn into Times (it looks like because they are somehow wrapped with the PostsItemsIcon component???)

image

**Comment by Raemon** [comment]
The "small devices" problem doesn't seem to be a problem:

image

**Pull request merged**
