### PR TITLE
Lighter Grey Background

### PR DESCRIPTION
**Pull request by Raemon**
Makes the background lighter, and adds some faint box shadows to help with the resulting contrast issues.

image

### CODE REVIEW

**Comment by Discordius** [comment]
Alas, I don't know man, I just tried it out and it just feels so much worse. I don't think we should merge this. We had all the discussion about the dropshadows, and while I didn't notice them in the screenshot (since screenshots are often lower resolution and have weird compression artifacts), they show up super hard on my machine, and I just have all the same objections.

**Comment by Discordius** [comment]
I am in favor of experimenting with different background colors and making things have more texture and stuff, but if this is what we have to do in order to make it lighter, then I don't think we should make it lighter, and instead search for different solutions.

**Comment by Raemon** [comment]
Alas.

So, I'm biased here because I actually just prefer this over status quo.

But, I think we should merge this for a week even if we just revert it a few days later. Partly, just to see how people react to it. But also to give people a sense that we are actually trying to iterate and find a thing that works. Some people responded positively to the new design, but we've gotten a nontrivial number of complaints about it, including from a few prominent LWers (at least 3?). 

I think it's ultimately fine to say "alas, we can't please everyone" or even "we think honestly you'll get used to this if you gave it a week, or are confused about what you don't like." But, for longterm goodwill I think it is fairly important to at least _try_ other things (during a period where we're actively rearranging the site a bunch, so I think we get more leniency for changing things), so that people can more easily believe "okay, they at least tried out alternatives."

I think, probably, there is somewhere-in-design-space a design that pleases everyone or at least avoids as strong a negative reaction. But I think it'll be a long while before we find it. Meanwhile, I think it's important that we re-roll on Frontpage Design at least slightly in the next week.

**Comment by Raemon** [comment]
(People who said they prefer the white background over grey background include Zvi, Robby, Elizabeth, Daniel Filan. I do think there's at least some amount of getting used to it that might happen. But I think Robby and Elizabeth at least both said so after a week)

**Comment by Discordius** [comment]
Hmm, I can see something in that space, but my model is that a larger number of users will be really annoyed if we are constantly moving the frontpage design around and changing everything slightly in a way that makes it hard for them to orient, which pushes in the opposite direction. 

It does seem like we would get more data if we go in this direction, so we could merge it for a bit.

I do remember Robby saying something about the grey being too droopy, but not sure whether he overall prefers it white. Seems plausible, and somewhat more likely than not, but we might just want to ask him.

**Comment by Raemon** [comment]
Yeah, I was simplifying positions a bit – Zvi and Daniel explicitly said they preferred the white, Elizabeth and Robby both said the grey felt dreary or something. Elizabeth also added that not having boxes around the posts list made it harder to parse (which I agree with).

**Comment by Raemon** [comment]
(I do agree it's also a bit annoying to change things a bunch, but I expect that right now it's good for people to model the site as in-flux, and it's better to make a bunch of changes now and then settle on the least-bad-one than to wait a couple months and then try again)

**Comment by Raemon** [comment]
Here's an alternate version where I do a softer box shadow – instead of thin and dark-enough-to-read-as-a-line, it's 5px, but mostly is there to subtly help the PostsItems pop out. Then, we can go back to having 2px borders that feel like "post items are separated" rather than lines.

image

**Comment by Discordius** [comment]
Cool, will check it out. Thank you for experimenting with this.

**Comment by Discordius** [comment]
Yeah, I think I am fine with this, and we can at least experiment with it.

**Comment by Raemon** [comment]
woo

**Pull request merged**
