### PR TITLE
Sequence navigation rework

### LINKED ISSUE #1089: Sequences bottom-navigation doesn't go between sequences in a book
Compare the top and bottom sequence navigations on eg https://www.lesswrong.com/rationality/many-worlds-one-best-guess ; the top navigation has a next-post link, while the bottom one doesn't.

### PR DESCRIPTION
**Pull request by jimrandomh**
Based off the partially-read sequences/continue reading PR, because of shared utility functions in `sequences/helpers.js`, but could potentially be merged independently. The first commit specific to this PR is "Add prevPost/nextPost resolvers to Post" (`d3f95c7`).

This cleans up a big piece of technical debt in sequence navigation, and fixes a few longstanding issues therein. Specifically, Posts now have resolvers `prevPost` and `nextPost`. They use our `extraVariables` HoC feature to take an optional sequence ID; if no sequence ID is given, it uses the canonical sequence ID. The posts-page fragment is modified to get sequence metadata, and the `PostsTopSequenceNav` and `BottomNavigation` are rewritten to use that rather than their own HoCs.

Fixes #1089 (bottom-navigation can't navigate across sequence boundaries). The sequence widget at the top no longer turns into a loading spinner when you navigate between posts.

### CODE REVIEW

**Comment by jimrandomh** [comment]
Planned next steps:
 * Add previous/next and collection links to sequence pages
 * Provide indication when you cross a sequence boundary. Maybe link to the next sequence's ToC instead of to the first post in it?

**Comment by jimrandomh** [comment]
Current status: Blocked on review and on https://github.com/LessWrong2/Lesswrong2/pull/1901 getting merged.

**Comment by Discordius** [comment]
This seems good, but will require merging with the changes I requested for #1901

**Comment by Discordius** [comment]
Not approving for now, to make sure we don't accidentally merge the PR this is based off

**Pull request merged**
