### PR TITLE
Move callbacks, views, resolvers to server directory

### PR DESCRIPTION
**Pull request by jimrandomh**
* ~Move all the `views.js` files into `server/views` (preventing their unnecessary execution on the client)~
 * Move all the `callbacks.js` files into `server/callbacks`
 * Move resolver files (under a variety of names) into `server/resolvers`
 * Convert all moved files to Typescript and fix up imports
 * Move `_id` from individual schemas to `addUniversalFields`

There is still a significant amount of resolvers (which should be server-specific) intermixed with the schemas and with other files; this PR doesn't separate those out, it only moves those that were already separated into their own files.

### CODE REVIEW

**Comment by Discordius** [comment]
Due to the use of mingo to filter client side lists we do indeed need the views on the client. I am pretty sure this would break any of the client-side updating of results when we get mutation results back from the server.

**Comment by jimrandomh** [comment]
Oh hmm. In that case, perhaps the correct thing is to include the views on the client, but defer their execution until the first incremental query update.

**Comment by jimrandomh** [comment]
I undid moving the views files (since it turns out they're actually necessary).

**Comment by Discordius** [comment]
Actually, the test failures seem real to me.

**Comment by jimrandomh** [comment]
I am very confused by what was going on with that unit test failure, but it was indeed real and this last commit fixes it.

**Pull request merged**
