### PR TITLE
Merge devel into master

### PR DESCRIPTION
**Pull request by Discordius**

### CODE REVIEW

**Comment by Raemon** [comment]
This looks overall good, but ended up with some stuff in it that should probably wait till tomorrow to merge. (Some of that my fault). 

Main thing I'm not sure how to evaluate is the notification batching. I just changed my own notification settings on lessestwrong but I'm not 100% sure what I'm supposed to be expecting.

**Comment by jimrandomh** [comment]
Fixed the warning, but meta-level, I strongly object to DeepScan warnings being a basis for blocking merge.

**Comment by jimrandomh** [comment]
By using the request-changes option in GitHub, you are not only saying "someone should address this", but saying "this may not be merged without my verifying that this has been addressed" (barring use of the administrator-override). That's not appropriate for lint warnings.

**Comment by Raemon** [comment]
Is there a way to remove an "approved" without saying "requested changes?"

**Comment by Raemon** [comment]
(I would quite prefer to remove any indication of my approval status one way or the other, but I don't know how to do it)

**Pull request merged**
