### PR TITLE
Enable table styling for CKEditor

### PR DESCRIPTION
**Pull request by Discordius**

### CODE REVIEW

**Comment by Raemon** [comment]
FYI, I tested this out, and found that I couldn't get the text-alignment to work quite right (I could get things to align right, and align-justify, and center, but not left, which was the one I wanted. Also when I aligned justified, the saved version didn't render the same as in the editor)

I think I _did_ verify that color was working, although I was sad that I couldn't appear to change the text color.

**Comment by Discordius** [comment]
Yeah, I don't want to activate the text-color plugin, because it made it so that copy-pasted text from GDocs had it's text color copied, which made everything look slightly off. 

Hmm, I didn't test text-alignment. Will fix.

**Comment by Raemon** [comment]
Hmm. Lack of color def seems fine for now, but is it possible to make it table-only? It limited my options a lot for the table styling since I couldn't have dark headers.

**Comment by Discordius** [comment]
I sadly don't know how to enable it just for tables.

**Comment by Raemon** [comment]
Alas. Well, ping me when you've doublechecked the text-alignment.

**Comment by Discordius** [comment]
Should now be fixed

**Pull request merged**
