### PR TITLE
Apollo 3 upgrade

### PR DESCRIPTION
**Pull request by jimrandomh**
Upgrade us to Apollo 3. This is not ready to merge; there are two known issues and it needs a fair amount of testing after that. The first issue is that we need to replace `FragmentMatcher`, the hack that enabled mutation responses to votes to be merged into the cache. The other is https://github.com/apollographql/apollo-client/issues/6651 .

### CODE REVIEW

**Comment by jimrandomh** [comment]
The apollo-client bug mentioned is resolved now. Performance measurements show ~20% better SSR time (I think mostly from flattening the prerender and render steps into a single pass), and comparable client script execution time. This is without making use of any of the newish cache object freezing options, which may improve performance further.

**Comment by jimrandomh** [comment]
This could use more QA, but there are no known issues outstanding.

**Comment by Discordius** [comment]
So, I was on this PR and hovering around on http://localhost:3000/allPosts?filter=untagged&timeframe=allTime&sortedBy=top when for some reason the post repeatedly went into a loading state every 3-4 seconds. 

I can reliably reproduce this, and it does not happen on current prod, so it's probably something to do with this update.

**Comment by Discordius** [comment]
Another bug: When I press "Load More" on the frontpage, the whole list disappears and is replaced with a loading state, then a longer list appears. Obviously that's not the intended result.

**Comment by Discordius** [comment]
The comment on this PR explains the behavior here pretty well:  

https://github.com/apollographql/apollo-client/issues/6760

Looks like the right fix is to add `nextFetchPolicy: cache-only` on basically all the instances of `fetchPolicy: cache-and-network`.

**Comment by Discordius** [comment]
And indeed, adding it appears to make the problem go away. I will do that on all the components I can find.

**Comment by Discordius** [comment]
The commit I added fixes all remaining issues I could find in components that use `useMulti`. However, there are still a 3 components that use `withMulti`, which are running into some problems related to the `loadMore` functionality. I could copy the relevant code over, but it might also just be best to make those components functional.

**Comment by jimrandomh** [comment]
The Load More behavior on the user profile page is currently surprisingly bad; if you click Load More on the comments list, it not only puts the comment list into a loading state and hides the comments, it somehow manages to also put the post list (an entirely separate query) into a loading state too!

**Comment by jimrandomh** [comment]
Ready for review. There was a weird bug that impacted everything which had `ssr: false` (which was the default), so I made `useMulti` not allow that as an option anymore.

**Comment by Discordius** [comment]
Test failure looks arguably real? Not fully sure.

**Comment by Discordius** [comment]
Yep, currently breaks, presumably because of a merge conflict

**Comment by Discordius** [comment]
(Pushed a commit that fixes it)

**Comment by Discordius** [comment]
Test failure looks real, but not catastrophic, will trust you to clean it up before merging

**Review by Discordius — APPROVED** [review]

**Pull request merged**
