### PR TITLE
Lifesize Images in Rich Editor

### PR DESCRIPTION
**Pull request by Raemon**
I think fixes the single biggest issue here:

https://github.com/LessWrong2/Lesswrong2/issues/1323

(Markdown users probably still want a preview but think this is most of the value)

### CODE REVIEW

**Comment by Discordius** [comment]
This seems like it's getting rid of the ability to resize them,  if I am not confused?

**Comment by Raemon** [comment]
Did we have the ability to resize them? I was not under that impression.

**Comment by Raemon** [comment]
I think I dispute that this could possibly have been working correctly, if the image on the editor doesn't correspond to the correct image size (as it is now). Maybe we want to make resizeable images but I don't think this is breaking something that currently works.

**Comment by Raemon** [comment]
(I have some sense of how to fix this for-actualz, but not sure if it's the sort of thing that's going to get undone when draft-js gets replaced)

**Comment by Raemon** [comment]
(last conversation was that Habryka thought it'd be fairly simple for them to fix this properly, so leaving the ball in their court)

**Pull request closed without merging**
