### PR TITLE
Don't use `Link` tags for relative links

### PR DESCRIPTION
**Pull request by Discordius**
Fixes footnote scrolling

### CODE REVIEW

**Comment by jimrandomh** [comment]
This appears to have overwritten/reverted the changes that were in https://github.com/LessWrong2/Lesswrong2/pull/2475 .

**Comment by jpaddison3** [comment]
Fixes https://github.com/LessWrong2/Lesswrong2/issues/2472

**Comment by Discordius** [comment]
Fixed

**Comment by Raemon** [comment]
deepscan issue looks real

**Pull request merged**
