### PR TITLE
gatherTownCron: Fix duplicate users when names change during check

### PR DESCRIPTION
**Pull request by jimrandomh**
Tested by: adding `getGatherTownUsers` to `Globals` and calling it from a `meteor shell`, while typing in the GatherTown username box in another window.

### CODE REVIEW

**Comment by Discordius** [comment]
Quite confident this changes the return type of the function you are modifying? It previously returned a dictionary from names to additional info. Not it just returns an array of names.

**Comment by jimrandomh** [comment]
Oops, you're right; my bad testing the function in isolation without checking closely. Will fix, and also type annotate it.

**Review by Raemon — APPROVED** [review]

**Comment by jimrandomh** [comment]
New testing strategy: shrink the cron-interval to 1 minute and connect to production, so that the local test server will run the cronjob before the production servers do. This way it's actually end-to-end.

**Comment by Raemon** [comment]
Whoops. Here I was approving based on Jim finally talking about how he tested a thing, like I wanted. :/

**Review by Discordius — APPROVED** [review]

**Pull request merged**
