### PR TITLE
EA Homepage 2

### PR DESCRIPTION
**Pull request by jpaddison3**
Add EA version of the Home2 component, for more freedom to diverge. Dynamic allPosts filters, and a frontpageAndMeta filter.
Plus a whitespace change because KHAAAAAN

### CODE REVIEW

**Comment by Raemon** [comment]
I think we should spend some time on Monday talking through this and what choices you're implicitly making – it probably makes sense to either remove or tweak some of the existing LW Home2 elements for EA forum.

**Comment by jpaddison3** [comment]
Slacking for coordination discussion

**Comment by jpaddison3** [comment]
See https://forum-staging.effectivealtruism.org for a preview.

**Comment by jpaddison3** [comment]
@Raemon the only merge conflict was because of the whitespace 🤦‍♂️

**Pull request merged**
