### PR TITLE
Centralize beta-gating in one file

### PR DESCRIPTION
**Pull request by jimrandomh**
Proposed convention: rather than stick `user?.beta && ...` in places, write a function `userHasMyNewFeature` in `betas.js` and import it. That way, we have a centralized list of features that are currently in beta, and an easy way to track down all the places to change when ungating things.

### CODE REVIEW

**Comment by Raemon** [comment]
Is the intent here to remove "userHasMyNewFeature" after launch, or is the feature forever centralized in this way?

**Comment by jimrandomh** [comment]
Yes, things will be removed after they no longer need to be gated.

**Comment by Raemon** [comment]
I'm still a bit unsure how much value this adds, and whether it's the right way to go about it if we're doing it. Would want to chat a bit about it first.

**Comment by Raemon** [comment]
(pushed a commit fixing merge conflicts)

**Pull request merged**
