### PR TITLE
Passport JS Authentication [WIP]

### PR DESCRIPTION
**Pull request by Discordius**

### CODE REVIEW

**Comment by jimrandomh** [comment]
Merged this from devel. There are a fair number of type errors, some of which are legit. One oddity that the type system turned up: ResolverContext isn't guaranteed to have a req/res because it can be used in cronjobs (eg rendering an email).

**Comment by Discordius** [comment]
Yeah, I also ran into that type error. I don't yet have a great idea for how to fix it, maybe just creating two types for ResolverContext and having the different functions annotated with the ones they need.

**Comment by jimrandomh** [comment]
It looks like account banning (from `banCallbacks.ts`) may have gotten dropped

**Comment by Discordius** [comment]
User bans are implemented in authentication.ts, IP bans are indeed removed and not yet implemented, but also maybe they were broken before?

**Comment by jimrandomh** [comment]
Are there changes in the version of `meteor/webapp` that's vendored in https://github.com/LessWrong2/Lesswrong2/pull/3651/commits/85d442d4ae43e1946b4bda8ffe041ea2e7807e01 ?
(In general, it's good practice to not vendor code and make other changes in the same commit, to make this obvious.)

**Comment by jimrandomh** [comment]
Merge conflicts between this PR and the webpack branch are pretty extensive. I'm not sure any sort of automatic merge is possible.

**Comment by jimrandomh** [comment]
Merge conflicts between this branch and the Webpack branch are pretty extensive. In retrospective, letting this sit unmerged for so long was a mistake.

**Pull request closed without merging**
