### PR TITLE
Add tag link

### PR DESCRIPTION
**Pull request by Raemon**
Creates a "view all tags" link in the "+ Add Tag menu", and then tried to clean up /tags/all slightly so it was less bad for users to see it.

### CODE REVIEW

**Comment by Discordius** [comment]
Can you post a screenshot? Just to verify the styling?

**Comment by Raemon** [comment]
Yeah. I'm still futzing around with it a bit because I wasn't satisfied. 

image

image

image

**Comment by Raemon** [comment]
Note: I tried doing the obvious things to improve the popper-placement on /tags/all on mobile, and it didn't work.

**Comment by Raemon** [comment]
I just incorporated the "tag search updates" that Oli and I chatted about on Tandem. After doing so, the new UI when you first click the 'Add Tag' button is:

image

**Pull request merged**
