### PR TITLE
Remove EA overloading of meta flag

### PR DESCRIPTION
**Pull request by jpaddison3**
Similar for EA overloading of personalBlog.

If I didn't make any mistakes, this should be a clean refactor for LW.

### CODE REVIEW

**Comment by Discordius** [comment]
Very exciting. Looks good to me. 

I do think the DeepScan errors are good to fix. Just a bunch of unused variables.

**Comment by jpaddison3** [comment]
Oops, I submitted at the end of the day and didn't see the failure. It would be nice if it showed up in our lint though.

**Comment by Raemon** [comment]
I believe there's a deepscan plugin for vs-code that detects errors automatically.

**Comment by jpaddison3** [comment]
Vscode already highlights the problems, but usually I delete a usage without knowing whether it was the last one, and don't go to the top of the file to notice.

**Comment by jpaddison3** [comment]
Deepscan still fake.

**Pull request merged**
