### PR TITLE
Remove voting from TagRelCard

### PR DESCRIPTION
**Pull request by Raemon**

### CODE REVIEW

**Comment by jimrandomh** [comment]
Uh, how exactly are you supposed to vote on tag relevance, then?

**Comment by jimrandomh** [comment]
If it's a core tag and it's at 1 relevance, this makes it basically impossible to ever upvote it--you'd have to go to the tag page and click Load More until you get to the bottom.

**Comment by Discordius** [comment]
Yeah, which for 90% of tags won't be a problem, and for the core tags basically isn't a real use-case that I expect anyone to try to do very much.

**Comment by jimrandomh** [comment]
No, being able to vote on relevance from post pages is a hard requirement. Wtf.

**Comment by jimrandomh** [comment]
If you hate the relevance-voting thing so much that you're willing to break it in order to keep it hidden, then we have to replace it with something else.

**Comment by Discordius** [comment]
No, like, I wouldn't be surprised if literally nobody who is not on the team has ever used it. And yes, we should indeed replace the relevance voting, that just takes time and we have other stuff to do.

**Comment by Raemon** [comment]
I'm closing this.

**Pull request closed without merging**
