### PR TITLE
Review Widget

### PR DESCRIPTION
**Pull request by Raemon**
Creates a (admin-gated) Review widget for posts with 2 or more nominations.

Uses similar architecture to the DialogManager

### CODE REVIEW

**Comment by Discordius** [comment]
Urgh, the Deepscan bug is real and will probably cause this to crash

**Comment by Discordius** [comment]
Will make another PR that fixes it

**Comment by Discordius** [comment]
Nevermind, was looking at a previous version of the PR

**Comment by Raemon** [comment]
Yeah, I fixed that before I left.

**Pull request merged**
