### PR TITLE
Update EA Forum links 

### PR DESCRIPTION
**Pull request by Xodarap**
The only UX change is on the EA Forum side, but this adds an ability for `HashLink`s to be external, which is shared functionality.

### CODE REVIEW

**Comment by Discordius** [comment]
I think this is a minorly bad change, though maybe overall better. I think it's good to be able to rely on `Link` components never actually causing a page navigation, and having a pretty strong divide between internal Links and external Links. 

Not confident though, and interested in @jimrandomh's thoughts. 

We can still easily preserve the specific functionality you want to have here by testing the link field on the routes object for being external, and displaying an `a` tag in that case.

**Comment by Xodarap** [comment]
Are you suggesting we change the component used in `TabNavigationItem` based on whether or not the link is external?

It intuitively seemed to me like the `Link` code is more "responsible" for ensuring that the correct link gets put into the document, so that's why I put it there, but I don't have a strong opinion either way.

**Comment by Discordius** [comment]
Yeah, currently the Link component is guaranteed to never end your session and cause a reload of the app. I think this is good and should stay this way. It's also keeping in line with the `react-router` API.

So yeah, currently to keep this a minimal change, I would just add a conditional to the TabNavigationItem

**Comment by Xodarap** [comment]
@Discordius sounds good, it's been updated now.

**Review by Discordius — APPROVED** [review]

**Pull request merged**
