### PR TITLE
Add special case for empty slugs (all unicode characters) in usernames

### PR DESCRIPTION
**Pull request by Discordius**

### CODE REVIEW

**Comment by Raemon** [comment]
...are... are you sure?

**Comment by Raemon** [comment]
Can you briefly describe what bug you experienced that this is fixing?

**Comment by jimrandomh** [comment]
Urgh. The whole username vs displayName vs slug thing is a really stupid piece of tech debt to have taken on, and I wish we could get rid of it. While this is a local improvement, I definitely don't feel good about it. I think it would be better for new accounts which would trigger this to fail validation.

**Comment by Discordius** [comment]
Sure, we can do that.

**Comment by Discordius** [comment]
Actually, I just disagree. I think that's more confusing.

**Comment by Discordius** [comment]
@Raemon: Concrete bug this was fixing: User created username with only unicode characters in it. When we tried to generate a slug for it, we generated "-60", which is an invalid slug, since relative links are not allowed to start with a dash, and chrome seems to automatically remove it, causing the link to break.

**Pull request merged**
