### PR TITLE
Add wiki grade system to tags

### PR DESCRIPTION
**Pull request by Discordius**
This adds a wiki-grade system to tags, including the ability to filter for the different grades on the All Tags page. Also fixes a bunch of misc bugs and inconveniences around tagging.

image

image

### CODE REVIEW

**Comment by Raemon** [comment]
Filtering thing a) should probably be in the reverse order (at least that feels intuitive to me) and I feel like it could be clearer whether it means "filter for things of this quality" or "things of this quality or above." But, maybe it'd work fine if there were actually tags of each type.

**Comment by Discordius** [comment]
Yep, makes sense, reversed the order in the menu

**Comment by Discordius** [comment]
Hmm, I can imagine a threshold feeling better, but not sure. I do really want to be able to select only the stub ones, so if we have that, I feel like I would also need a "this and below" operator, and then it gets too complicated, so I prefer just doing the single-select thing for now.

**Comment by darkruby501** [comment]
The use-cases seem to be "taggers wanting to find stuff to work on" and "readers wanting to find the good tags to look at"

**Comment by Raemon** [comment]
Approved, but merge devel into master first if you haven't yet

**Pull request merged**
