### PR TITLE
Merge devel into master

### PR DESCRIPTION
**Pull request by Discordius**

### CODE REVIEW

**Comment by jimrandomh** [comment]
Why was the license.md change pushed directly to devel rather than going through a PR that can be reviewed? That's how the license-file situation got fucked up in the first place. Revert and do it properly, please.

**Comment by Discordius** [comment]
Default setting in the Github change UI

**Comment by Discordius** [comment]
What... would the possible reason be for reverting it and doing it otherwise? You've seen the change, you know what it is, you can review the commit as part of this PR.

**Comment by Discordius** [comment]
Will merge this tomorrow unless someone objects

**Pull request merged**
