### PR TITLE
Fix interaction of shortform and spam

### PR DESCRIPTION
**Pull request by Discordius**

### CODE REVIEW

**Comment by Discordius** [comment]
Also adds some error logging to server-side graphQL errors

**Comment by Raemon** [comment]
Is the new behavior that users creating new shortform posts appear as New Users in the sunshine sidebar, or some other thing?

**Comment by jimrandomh** [comment]
I don't really understand what this PR is doing. Clarify?

**Comment by Discordius** [comment]
There was a bug, where a bunch of post-callbacks were relying on having a `currentUser` in context. In particular the akismet spam-check bug, would refer to `currentUser.karma` in the callback, when it did register a comment as spam. This caused some users to fail to be able to create shortform posts, because akismet would classify their comment as spam, which would then cause the whole callback chain to crash, resulting in a shortform post but without the shortformId being set on the user object, and without the intended comment being added to that post, and the user being presented with an error message that said `couldn't read property karma of undefined`

**Comment by Discordius** [comment]
See this Intercom conversation for context: https://app.intercom.io/a/apps/wtb8z7sj/inbox/inbox/all/conversations/24693308523

**Pull request merged**
