### PR TITLE
Distinguish tag types with styling

### PR DESCRIPTION
**Pull request by jimrandomh**
Sort core tags and the frontpage/personal marker to the end of the tag list in post headers/footers, and style them differently. This makes it easy to see which tags are non-core tags, which are likely to be the most interesting ones.

DistinguishTagTypes

(Feel free to suggest different colors.)

### CODE REVIEW

**Comment by jimrandomh** [comment]
It's plausible to me that the right order is actually (Frontpage) (Non-core) (Core) or even (Frontpage) (Core) (Non-core); the important thing is that core and non-core aren't intermixed.

**Comment by Raemon** [comment]
This particular version seems too intense, but I think there's a nearby version that is subtler but still functional, which I'll work on in a bit.

I actually would do: [core][non-core][frontpage]. It feels really weird to me to sort the core tags to the end – it's sending confusing messages about how important they are. (I say that while agreeing that actually the non-core tags should be where you end up focusing most on)

**Comment by Discordius** [comment]
I mean, this styling kind of obviously doesn't work, if only because it imports two colors we've never used anywhere else. I think it's unlikely we want to give the core tags or the frontpage tag colors, because that makes them stand out more, not less, but not super confident. We might find a color that deemphasizes them. 

I do think I prefer [non-core][core][frontpage].

**Comment by Raemon** [comment]
Here is one attempt I made:

image

**Comment by Discordius** [comment]
Yeah, I can imagine something like that working out. Not sure whether the thing is yet fully good enough. Frontpage one feels a bit weirdly weak, and the contrast between the green and the black for the Community one also seems a bit too weak, but not sure.

**Comment by darkruby501** [comment]
That makes the community tag more promiment rather than less. I could see styling Core the same as Frontpage being maybe good.

**Comment by darkruby501** [comment]
To be clear, I think it's really, really bad to make the core tags more prominent looking (and my first preference would still be to hide them).

**Comment by Raemon** [comment]
(had this written up before other people commented) 

Figuring out what to do with the Core Tags feels tricky to me: I think it's fairly important we use the same visual language for Core Tags everywhere. Whatever their styling here is, should probably be the same on the Home page.

I think it's pretty weird for the visual language to make Core Tags feel less important than regular tags. Yes, they're less important for parsing the post, but they're more important/central _concepts_ than the other tags. 

It seems like the Core Tag styling needs to somehow be "neutrally important looking", while remaining distinct.

**Comment by Raemon** [comment]
Dunno if this solves problems anyone has, but I do like it somewhat better than previous one:

image

**Comment by Raemon** [comment]
Here's the latest version, which I think is basically ready to merge. I also changed the styling the for the Frontpage/Personal tooltip to match the other tags. (I think it might be nice to add a "moderator only tag" label to the tooltip, but that was more of a Decision so I figured I'd hold off for now)

image

**Comment by darkruby501** [comment]
Looks pretty good to me.

**Pull request merged**
