### PR TITLE
RecommendationsAndCurated

### PR DESCRIPTION
**Pull request by Raemon**

### CODE REVIEW

**Comment by Raemon** [comment]
(Note: in the current version I've removed the NoSSR tag, mostly to trigger a discussion about what it's doing and what we're waiting on to remove it. I think for actually pushing recommendations it seems important to not have it.

I do observe that it seems to load pretty quickly and straightforwardly when I remove the tag (on the development db) so was somewhat confused about it, although I assume it's doing something important)

**Comment by Raemon** [comment]
image

**Comment by Raemon** [comment]
@jimrandomh – Oli looked over the NoSSR stuff and it seemed safe to remove. Doublechecking with you that it seems sane tho.

**Comment by Discordius** [comment]
Mrrr, doesn't this have like 60 copied lines from the current `RecommendationsList`?

**Comment by jimrandomh** [comment]
Hmm, yes, there's copy-paste here from `ConfigurableRecommendationsList`. I think there's a worthwhile refactor in making a component for the "section with gear icon that opens an expander" pattern (used here, and also on the allPosts page).

**Comment by jimrandomh** [comment]
The `changeSettings` and `getCurrentSettings` functions could be extracted to top-level so that they can be imported/shared.

**Comment by Discordius** [comment]
This would be pretty easy to refactor if we had hooks, since that allows you to abstract state-manipulations. As is, an HoC might be the correct choice (with a `getSetting` and `setSetting` variable that gets passed down).

**Comment by jimrandomh** [comment]
Regarding SSR: It looks like what actually happens, is that it fetches once and doesn't refresh when you navigate back to home. The "render recommendations and then rerender a different set" problem was in some other version (maybe different fetch settings?) and doesn't manifest here. It still isn't ideal because the recommendations *should* refresh when you come back to home from somewhere else, but it's significantly better than I thought it would be.

**Comment by Discordius** [comment]
We can just trigger the refetch manually on a navigation event by registering a client-side callback on a  navigation event and checking for home. Or figure out how to distinguish the initial mount from following ones and refetch there.

**Comment by Raemon** [comment]
So, the intent with this PR is basically to move ConfigurableRecommendationsList into obsolesence, but like PostsItem (vs PostsItem2) before it, it's just not quite ready to be deprecated. I don't think we'll ever actually ship ConfigurableRecommendationsList as a user-facing component – it's too opinionated about it's UI.

[fake edit: hmm – I guess it's still in use on the literal recommendations page. I'm not sure how important that page actually is though]

**Comment by Raemon** [comment]
> It still isn't ideal because the recommendations should refresh when you come back to home from somewhere else, but it's significantly better than I thought it would be.

I don't think I actually want this though – I already prefer to get less rather than more recommendations to avoid bottomless-content-syndrome.

**Comment by Raemon** [comment]
(Also, I can't tell if this is actually approved or not given the followup discussion)

**Comment by Discordius** [comment]
I think the duplicate code thing is important enough to fix or at least reduce that I would not approve it.

**Comment by Raemon** [comment]
Okay, more concretely: My proposal is, rather than reduce duplicate code, just delete ConfigurableRecommendationsList, and remove the /recommendations page. (Unless we are confident we really want the recommendations page)

**Comment by jimrandomh** [comment]
I think we really do want the recommendations page. This seems like an opportunity to level up at refactoring.

**Comment by jimrandomh** [comment]
The refactoring is good (we paired on it), just need to lint and this can merge.

**Pull request merged**
