### PR TITLE
SequencesGridItem has new styling (removing padding)

### PR DESCRIPTION
**Pull request by Raemon**
This is partly in preparation for an overall frontpage redesign

image

image

image

┆Issue is synchronized with this [Trello card](https://trello.com/c/C3hoocEj) by [Unito](https://www.unito.io/learn-more)

### CODE REVIEW

**Comment by Discordius** [comment]
(Not a huge fan of the permanently grey background and the dropshadow. My guess is the plan is to get rid of the dropshadow as soon as we make all the background grey?

**Comment by Raemon** [comment]
Right now the purpose of the grey-image-background is specifically so the image stands out a bit more. It might be that this will become unnecessary as soon as we move to the grey-background overall.

It might also actually be unnecessary to have _both_ the dropshadow and the slightly-grey-background. Dunno. I do expect this to be mostly temporary.

**Comment by Discordius** [comment]
Yeah, I do think I care enough about it to remove it. I do think it's unnecessary as long as we have the dropshadow.

**Comment by Raemon** [comment]
Updated it to have a much lighter background that disappears when the image loads

**Comment by Raemon** [comment]
If we end up deploying this to master before the frontpage redesign is done, I might manually just make Predictably Wrong have a darker image so it looks a more harmonious with the other images

**Pull request merged**
