### PR TITLE
Support EA customization of PostsTimeBlock

### PR DESCRIPTION
**Pull request by jpaddison3**
Mostly this is just a little bit of DRYing up in a way that allows for customization based on forumType. ~There are some useful behavior changes. PostsTimeBlock now has a separate section for meta posts, and meta posts no longer display both the Personal and Meta icons.~

### CODE REVIEW

**Comment by Raemon** [comment]
(Told JP in person but noting here, LW is most likely deprecating meta, or at least trying not to be oriented deeply around it, so the parts of this code that lean towards "building more explicit infrastructure for meta on LW" seem like they should change)

**Comment by jpaddison3** [comment]
@Raemon Still curious if you want to change the alignment forum ContentType tooltips.

**Comment by Raemon** [comment]
Oh, hrm. We probably actually don't want AlignmentForum to have any frontpage/personal distinctions (the incentives are all different there). But I think that's on us to deal with, and this PR seems mostly like an improvement over status quo.

**Comment by jpaddison3** [comment]
Note that Alignment Forum does have an allPosts page that at least Vanniver uses.

**Pull request merged**
