### PR TITLE
Fixes and refactors for Apollo 3

### PR DESCRIPTION
**Pull request by jimrandomh**
Fixes a bad load-more experience on the All Posts page. Fixes a bad loading state after voting on tag pages.

The load-more problem on the All Posts page was caused by using `withMulti` (as opposed to `useMulti`), which is missing some of the fetch-policy handling that `useMulti` does. This was the last user-facing use of `withMulti`, so I just went ahead and hookified the component.

The loading state after voting on tag pages turned out to be caused by unnecessary subfragments in the `WithVoteTagRel` fragment; since the vote mutation is presumed to return `WithVoteTagRel` and this has the associated tag expanded as a subfragment, it would dirty the tag in the cache when the mutation went out, which put the whole page in a loading state. This subfragment were actually totally unnecessary (according to typechecking), so I trimmed that fragment down to a minimal set of fields.

I noticed a number of SSR mismatch warnings, specifically occurring when the result DOM has consecutive text nodes. Eg
```
<div>{"Hello "}{"World"}</div>
```
would generate the HTML
```
<div>Hello World</div>
```
which is technically an SSR mismatch, because there's one text node instead of two; it should instead have generated
```
<div>Hello <!-- -->World</div>
```
As it turns out, this was a consequence of using getDataFromTree instead of renderToStringWithData. According to https://www.apollographql.com/docs/react/api/react/ssr/ the difference between those is whether it uses 'ReactDOMServer.renderToString' or 'ReactDOMServer.renderToStaticMarkup'; React's docs describe the latter as only suitable for generating noninteractive HTML. Switching to the correct API fixes this error and doesn't cause any problems I can see.

### CODE REVIEW

**Comment by Discordius** [comment]
I seem to be reliably getting infinitely repeating recent discussion on this branch.

**Comment by Discordius** [comment]
And alas, the voting error still occurs on this branch. I.e. on certain threads when I vote on them, my vote continues to be undone after the server response comes back.

**Comment by Discordius** [comment]
(Copied from Slack for posterity: 

> Also, I am getting some really weird infinite scroll behavior on the apolloFixes branch. I sometimes scroll down, but when the new items render, I get thrown back completely to the top of recent discussion again, in some kind of loading state

> Seems to reliably reproduce for me

> based on the description of the PR, there is an underlying cause to a lot of these issues, which is that in Apollo 3, when you dirty the cache on a cache-and-network component, it reloads the data and goes back into a loading state, which I think is just really not what we want. I mean, it would have been a fine thing to design around, but given the decisions we've made with the old way of how things work, it's really hard to spot all the places where that's causing problems

**Comment by jimrandomh** [comment]
Neither of those bugs are related to this PR. (I speculated that this PR might fix the voting bug, since it changes voting code heavily, but the voting bug appears to already be in prod so it predates our use of Apollo 3.)

**Comment by Discordius** [comment]
Yep, seems unlikely to be related to this PR. I think everything in this PR is fine, though of course there are other problems remaining in current devel.

**Review by Discordius — APPROVED** [review]

**Comment by Discordius** [comment]
Wait, did we check whether the change to `renderToStringWithData` doesn't run into the className problems we talked about? This PR doesn't seem to address those.

**Comment by jimrandomh** [comment]
I believe the conclusion was that changing to `renderToStringWithData` would run into problems iff there were components using numbered/unnamed classes, and material-UI's Hidden was the only thing doing that. So should be good when paired with https://github.com/LessWrong2/Lesswrong2/pull/3650 .

**Pull request merged**
