### PR TITLE
Automatically insert hyperlinks on user raw link input

### PR DESCRIPTION
**Pull request by jpaddison3**
Markdown was suuuuper easy. Draft js had a weird problem where the plugin only changed the rendering and did nothing to the content. We use the same library as the plugin to identify and autolink links.

Limitations: 
 - If you try to insert a link on top of your link it's not very natural.
  - Does not perform autolinking on historical text.

I thought I'd write some tests but I decided that meteor testing is literally the devil. I'm kinda asking for help, but might also trash the test file. Kinda curious to see if I wrote it correctly anyway.

### CODE REVIEW

**Comment by Discordius** [comment]
Wait, given that we are doing all of this in parallel now, do we actually need to copy the `linkify-plugin` code? I don't think we are making any modifications to it, so pinning it seems better than copying it.

**Comment by jpaddison3** [comment]
Hmm, I was assuming past me had a reason for this. Maybe it was just to edit the code. Will look further into this.

**Comment by jpaddison3** [comment]
@Discordius ready for re-review. Sorry I didn't notice the weirdness of code copypasta earlier.

**Comment by jpaddison3** [comment]
@Discordius ready for rereview

**Comment by Discordius** [comment]
@jpaddison3: Lol, you deactivated all unit tests except your own :P

**Comment by Discordius** [comment]
Sneaky way to get past the tests

**Comment by jpaddison3** [comment]
I remember removing that -----

**Comment by jpaddison3** [comment]
There it is. It's not there in the EA Forum code. I committed it to the wrong branch or something? Alright, I'm getting a checklist back.

**Comment by jimrandomh** [comment]
This PR introduced a cross-site scripting vulnerability, and we have reverted it on Less Wrong production. EA Forum does not currently seem to be impacted, because it wasn't merged there. Don't merge it until the vulnerability is fixed.

**Pull request merged**
