### PR TITLE
[TESTME] Apollo 2 upgrade

### PR DESCRIPTION
**Pull request by jimrandomh**
See also the Vulcan side of this PR: https://github.com/LessWrong2/Vulcan/pull/73

Status notes:

- [x] ~GraphQL queries aren't batched~
- [x] Numerous broken links and incorrect URL handling due to unhandled route and query params. Need to finish systematic pass through withRouter usages.
- [x] Comment box padding is drastically expanded
- [x] Custom post-submit button (with "moderators may promote" and "save as draft" options) isn't getting used for some reason
- [x] Post-view event recording is stubbed
- [x] The helpText tooltip on moderation guidelines is missing (was a vulcan-forms hack)
- [x] Edit Account SSR crashes, something related to karma-change notifier
- [x] User account page form submission is broken
- [x] EditSequenceTitle styling is broken
     MUI is taking precedence over SCSS styles, causing incorrect font size
- [x] Edit-post page is broken
     Navigation doesn't set query parameters
     Probably lots more wrong
- [x] On new-post page: Mysterious SSR mismatch
     Console displays: Warning: Prop `className` did not match. Server: "Textarea-textarea-229 Textarea-shadow-230" Client: "Textarea-textarea-263 Textarea-shadow-264"
- [x] Markdown editor displays a second copy of its contents above the edit box
- [x] getHeaderSubtitleDataFromRouterProps is stubbed 
- [x] Email rendering is broken
- [x] Navigating to a related question crashes with `Error: TypeError: this.props.closeAllEvents is not a function`

Form submission problems:
- [x] Submitting an Answer mis-detects which editor is active and submits a comment instead
- [x] Submitting a question creates a non-question post (`prefilledProps` doesn't work)
- [x] Submitting a draft makes a non-draft post (setting fields in submit-button `onClick` doesn't work)

Wrapping react-router turned out not to be sufficient for or a good strategy for dealing with the differences, which, it turns out, go significantly deeper than just property renames. Instead, usage of `reactRouterWrapper` is now serving as a marker for which files still need to be gone over to fix their react-router usages.

### CODE REVIEW

**Comment by Discordius** [comment]
`Utils.manualClickNavigation` is broken, probably because it relies on some no longer supported `react-router` properties

**Comment by jimrandomh** [comment]
It is likely not `Utils.manualClickNavigation` being broken, but the parameters it's being passed. (Particularly the third paramater. `router.push` no longer exists, but `history.push` does.)

**Comment by jimrandomh** [comment]
- [ ] Navigating to a related question crashes with `Error: TypeError: this.props.closeAllEvents is not a function`
- [ ] Submitting an Answer mis-detects which editor is active and submits a comment instead

**Comment by Discordius** [comment]
Note: We will need to run the `fixDeletedBios` migration script before we merge this

**Comment by jimrandomh** [comment]
Unit tests pass! (Run locally, with the correct Vulcan repo branch.)

**Comment by jimrandomh** [comment]
- [ ] SSR crashes if any users have htmlBio that isn't a string (and DB contains a bunch of users with that property)

**Comment by Discordius** [comment]
Problem: Everything that calls `getHeaderSubtitleDataFromRouterProps` doesn't currently work because of changes in the router API

**Comment by jimrandomh** [comment]
- [ ] SSR crashes if any users have htmlBio that isn't a string (and DB contains a bunch of users with that property)
- [x] Crashes in `withDelete` in many places
- [ ] The new-post form has a section labelled "Options" containing the coauthors field, which has a collapse arrow but doesn't collapse
- [x] `/shortform` crashes
- [ ] Switching the editor-type from draftjs to markdown in the comment editor crashes

**Comment by jimrandomh** [comment]
- [ ] Subtitles are broken

**Comment by jimrandomh** [comment]
- [ ] Change react-router usage to avoid remounting Layout
- [ ] `getHeaderSubtitleData` crashes on user-profile with `Users.findInStore is not a function`

**Pull request merged**
