### PR TITLE
Fix for missing author in RSS feed posts

### PR DESCRIPTION
**Pull request by crybx**
A fix for [issue 210](https://github.com/Discordius/Lesswrong2/issues/210) and its duplicate, [issue 543](https://github.com/Discordius/Lesswrong2/issues/543).

Post.author is null in the database for most posts. (The pattern I think leads to the few posts having an author set is moving posts around, e.g. move to frontpage, curate, or sticky seems to cause the author to populate.)

This pull request would make
```
<dc:creator>
    <![CDATA[ username ]]>
</dc:creator>
```
show up for every post in RSS regardless of whether the author field has ever been populated.

(I'm not sure if there's a different, more preferred way to handle this without editing example-forum since there's no custom lesswrong rss stuff.)

### CODE REVIEW

**Comment by Raemon** [comment]
@Discordius can you take a quick look at this? I'm not familiar enough with the RSS to tell if this is the right approach.

**Comment by Discordius** [comment]
I will have to test it, hope to get around to that tomorrow. You should also remove the String literal around the Users.getUserNameById, since getUserNameById already returns a string.

**Comment by Raemon** [comment]
(just wanted to apologize for us not having gotten around to this yet)

**Comment by Discordius** [comment]
So, this seems almost correct. I looked a bit into just making the author field reliable, but I don't think that's worth it, and we should probably just deprecate the whole field. 

The most important change to your code, is to use displayName instead of username. The username is something we use on the backend to have unique identifiers, the displayName is actually the one that you see all over the site. I think this should work like we expect it to after that small fix.

**Pull request closed without merging**
