### PR TITLE
All posts page improvements

### PR DESCRIPTION
**Pull request by jimrandomh**
Adds a comment-count icon to single-line shortform comments on the All Posts page, so you can tell there are replies. Adds a "Wiki/Tag Page Edits and Discussion" section to the All Posts page (daily view only). Entries in this section are wiki/tag pages; in the right column it shows size of edits (words added/removed), and number of comments in threads that were started on that day. When expanded, it shows the diffs and the discussion comments.

This PR represents one day of dev (taking a break from Rationality Cardinality and my rationality-testing project to get back to LessWrong). It could use a styling pass, and a few small tweaks like properly linkifying things. A nice longer-term piece of development would be to make the comment bubbles turn green when there are new comments on something you've already read, like PostsItem does.

### CODE REVIEW

**Comment by Discordius** [comment]
Nice! 

> Adds a comment-count icon to single-line shortform comments on the All Posts page

I... can't find this purported comment-count icon. Presumably this is because the migration hasn't been run on the production server? Seems fine to run it, I think it's very likely we will merge this in some form or another.

**Styling thoughts:** 
[ ] The single-line tag-edit really needs to change the cursor to a pointer. Currently super not obvious you can click on it.
[ ] The tag title should be displayed in sans-serif small-caps. The serif doesn't read well-enough at that font-size, and we use small-caps for the tag titles, which I think makes them meaningfully distinct.
[ ] We need to somehow get rid of one of the borders in the expanded single-line tag item. The two borders sure look janky (see screenshot below)
[ ] Less confident of this, but I really feel like there should be some better way to get to the actual tag page for the edit than clicking on the discussion link.
[ ] The spacing and sizing of the single-line tag item should look more similar to the spacing and sizing of the single-line comments item. Currently they look very slightly different in a way that looks unintentional. See second screenshot below.
[ ] The spacing on the "Discuss this tag" button and the number of comments in the thread seems broken. See screenshot 3 below
[ ] The Change-Metrics display is in Times New Roman and should be changed to our sans-serif font


image

image

image

**Comment by jimrandomh** [comment]
It does require the migration, but the migration shouldn't be run until after merge (because it fills in a field that requires incremental updating, and the old version won't do the incremental updates). The easiest way to see it is on the dev DB, where you can create shortforms and reply to them willy nilly (and there's already some there from my testing). Note that the migration is quite slow, ~10h, but fortunately it's idempotent/incremental and saves partial progress. I ran it on the dev DB overnight.

**Comment by jimrandomh** [comment]
(Also note: I'm shifting back to my rationality-testing project, and explicitly not committing to followup on this within the next week. I took a break from that to do a day of dev on LW, mainly to distinguish "working on the LW codebase is draining" from "working with the LW team is draining". I think this was moderate evidence for the latter.

**Comment by jimrandomh** [comment]
Collapsed:

Screen Shot 2021-05-08 at 13 05 52

Expanded:

Screen Shot 2021-05-08 at 13 06 33

I'm a bit dissatisfied with the title in the expanded view, which looks kind of misaligned (its alignment having been determined by what works in the collapsed view, and them being the same). The collapsed view looks a bit like something's missing; the titles are too far left, relative to shortforms. But I tried adding a tag icon on the left, similar to the shortform icon on those single line comments, and the tag icons everywhere looked worse. I think this is good enough for now, but not necessarily final.

**Comment by Discordius** [comment]
Hmm tests are failing. Output is a bit spammed because of that one Database setting that's not initialized early enough, so not fully sure what the cause is, but looks maybe kind of real.

**Comment by Discordius** [comment]
Seems good to merge after looking into the failing tests.

**Pull request merged**
