### PR TITLE
Fixed position posts menu

### PR DESCRIPTION
**Pull request by Raemon**
We've been accumulating menu items, and now frequently the post-menu item appears at random, unpredictable positions because Popover attempts to place itself fully visible on the screen. 

This migrates the menu over to the LWPopper system rather than Popover so we can control it the same way we control similar elements, and fixes some random bugs that came up in the process.

### CODE REVIEW

**Comment by Discordius** [comment]
Did you test that it doesn't break when opened at the bottom of a page?

**Comment by Raemon** [comment]
I did not, thanks. Also felt like it was slightly off in general and want
to spend more time thinking about it

**Comment by Raemon** [comment]
Just checked, it actually works pretty well – it increases the height of the page and you can scroll down like normal.

**Comment by Raemon** [comment]
@Discordius reminder to either give a more concrete concern or approve this.

**Comment by jimrandomh** [comment]
This broke the post-actions menu (clicking on items in the menu closes the menu, without registering the click).

**Pull request merged**
