### PR TITLE
Frontpage Complete Overhaul

### PR DESCRIPTION
**Pull request by Raemon**
image

image

┆Issue is synchronized with this [Trello card](https://trello.com/c/KTVTMnAw) by [Unito](https://www.unito.io/learn-more)

### CODE REVIEW

**Comment by darkruby501** [comment]
@Raemon Following up on previous thread, this is an example where more differentiation in the PR title would be helpful to me in tracking the PRs, e.g. something like _Frontpage Redesign: Grey Background/SequenceGrid/Card-like Appearance_ or something.

The included images help, but if I look at them I'm likely to forget when I see the PR again later. Detail which differentiates _which_ Frontpage Redesign PR this is therefore quite helpful.

**Comment by Raemon** [comment]
I don't really think that's tractable – this is the sort of thing where it's very likely that the details will change, possibly with several drastically different sets of images tried out over the course of the PR's history.

I think it might be possible to set the title to "whatever the PR ends up being" for posterity, after it's finished. I can tell you what I think the styles are going to be when I start out, but those often change and seem more likely to mislead than to help to me.

**Comment by darkruby501** [comment]
Makes sense. In that case I'd make the bid for something like "Frontpage
Redesign May/June #2" with a description that is kept up to date with the
rough scope of the changes.

Changing name for posterity upon completion also makes sense: easy to go
back and find the PRs where certain changes happened, especially if there's
discussion in them we might later want to find.

**Comment by Discordius** [comment]
I feel pretty strongly that we want to keep the designs flat. I.e. no drop-shadows in the recent discussion section and on the post-items. 

I think it's more OK in the Recent Discussion section, but is quite bad in the PostsItems, at least if I am parsing the current screenshots correctly (none of them have a full PostsList, so it's somewhat hard for me to tell). 

It's plausible that we would want to add dropshadows, but I think it would be quite a big decision that would affect a lot of things, and I think would overall make the site a lot more cluttered in the same way that the post-item borders made it a lot busier. 

There is a thing that I am more open to, that is to have some kind of dropshadows on complete post-lists, making them a more unified item. That's what ProductHunt does, and it works decently fine (though I think I would still a prefer a flat aesthetic).

**Comment by Discordius** [comment]
Also, moving all the tags on one line is pretty crucial as is making their background more grey.

**Pull request closed without merging**
