### PR TITLE
Fix collectionTypes

### PR DESCRIPTION
**Pull request by jpaddison3**
`collectionTypes.d.ts` had type errors. Why weren't those errors caught by checktypes? For type checking, we run `tsc --noEmit --noLibCheck`. --noLibCheck is designed to prevent us from having to be bothered by the `@types/npm_module`s having problems. Unfortunately, the way it does this is by excluding all .d.ts files, including ours. I believe the best way to fix this is to simply move collectionTypes to a .ts extension, as it's all perfectly valid typescript. I did so, and fixed the type errors. 

Note: I did not do this for our generated type files, which also have errors.

While investigating an undefined WriteResult type, I discovered something sad. Per https://github.com/meteor/meteor/issues/4436#issuecomment-283974686, Meteor does not return anything similar to a MongoDB WriteResult. It returns a number. That number is not what we assumed, which was the nModified field of WriteResult. Rather it is apparently the less useful nMatched. I updated some code in `migrationUtils.ts` to reflect this.

### CODE REVIEW

**Comment by jpaddison3** [comment]
Merge at your leisure.

**Comment by Discordius** [comment]
Alas, merge conflicts. Fixing them would be appreciated, but I will probably also get around to it in the next few days.

**Comment by jpaddison3** [comment]
C'mon guys...

**Comment by jpaddison3** [comment]
Fixing merge conflicts only to have more merge conflicts arise before it get's merged.

It's like making yourself a nice sandwich and then dropping it on the floor.

And it feels totally unnecessary for such a simple PR.

**Comment by Discordius** [comment]
Weekends are a bit harder to coordinate around. But seems fair.

**Comment by jpaddison3** [comment]
You could say it's my fault for doing it on a Friday when y'all are off filosophizing. I probably should have waited till Monday.

**Pull request merged**
