### PR TITLE
All the PRs, merged together for testing purposes

### PR DESCRIPTION
**Pull request by jimrandomh**

### CODE REVIEW

**Comment by Discordius** [comment]
When accessing the New Posts form: 



```
Uncaught TypeError: Cannot read property 'map' of undefined
    at FormComponentSelect (FormComponentSelect.tsx:11)
    at renderWithHooks (modules.js?hash=d213eed66c2fd7b2cc1cbec1dad73e0b9d56a01f:129058)
    at mountIndeterminateComponent (modules.js?hash=d213eed66c2fd7b2cc1cbec1dad73e0b9d56a01f:131292)
    at beginWork$1 (modules.js?hash=d213eed66c2fd7b2cc1cbec1dad73e0b9d56a01f:132436)
    at HTMLUnknownElement.callCallback (modules.js?hash=d213eed66c2fd7b2cc1cbec1dad73e0b9d56a01f:114297)
    at Object.invokeGuardedCallbackDev (modules.js?hash=d213eed66c2fd7b2cc1cbec1dad73e0b9d56a01f:114347)
    at invokeGuardedCallback (modules.js?hash=d213eed66c2fd7b2cc1cbec1dad73e0b9d56a01f:114404)
    at beginWork$$1 (modules.js?hash=d213eed66c2fd7b2cc1cbec1dad73e0b9d56a01f:137167)
    at performUnitOfWork (modules.js?hash=d213eed66c2fd7b2cc1cbec1dad73e0b9d56a01f:136158)
    at workLoopSync (modules.js?hash=d213eed66c2fd7b2cc1cbec1dad73e0b9d56a01f:136135)
```

**Comment by Discordius** [comment]
Sunshine Sidebar is now in Times New Roman:

**Comment by Discordius** [comment]
Trying to submit a comment results in: 

image

**Comment by Discordius** [comment]
Times New Roman on User Profile page: 

image

**Comment by Discordius** [comment]
Times New Roman on PostItems: 

image

Ok, I won't report any more Times New Roman font bugs. Presumably they have a central source in the refactored Typography component.

**Comment by Discordius** [comment]
Editing comments does not cause the comment to change. It appears to have no effect.

**Comment by Discordius** [comment]
All Tags page is broken (with the options error, so presumably because there is some kind of form on it)

**Comment by Discordius** [comment]
Editing sequences does not have an effect (presumably same error as comments editing having no effect)

**Comment by Discordius** [comment]
All Posts page breaks with error: 

image

```
AllPostsPage.tsx:62 Uncaught TypeError: updateCurrentUser is not a function
    at AllPostsPage.<anonymous> (AllPostsPage.tsx:62)
    at callCallback (modules.js?hash=d213eed66c2fd7b2cc1cbec1dad73e0b9d56a01f:126879)
    at commitUpdateEffects (modules.js?hash=d213eed66c2fd7b2cc1cbec1dad73e0b9d56a01f:126918)
    at commitUpdateQueue (modules.js?hash=d213eed66c2fd7b2cc1cbec1dad73e0b9d56a01f:126906)
    at commitLifeCycles (modules.js?hash=d213eed66c2fd7b2cc1cbec1dad73e0b9d56a01f:134029)
    at commitLayoutEffects (modules.js?hash=d213eed66c2fd7b2cc1cbec1dad73e0b9d56a01f:136763)
    at HTMLUnknownElement.callCallback (modules.js?hash=d213eed66c2fd7b2cc1cbec1dad73e0b9d56a01f:114297)
    at Object.invokeGuardedCallbackDev (modules.js?hash=d213eed66c2fd7b2cc1cbec1dad73e0b9d56a01f:114347)
    at invokeGuardedCallback (modules.js?hash=d213eed66c2fd7b2cc1cbec1dad73e0b9d56a01f:114404)
    at commitRootImpl (modules.js?hash=d213eed66c2fd7b2cc1cbec1dad73e0b9d56a01f:136535)
```

**Comment by jimrandomh** [comment]
(Unit test failure is a legitimate bug from upstream, not introduced in this PR, detected by new typechecking covering views.)

**Pull request merged**
