### PR TITLE
Un-gate single-line comments

### PR DESCRIPTION
**Pull request by jimrandomh**
Probably ready.

### CODE REVIEW

**Comment by Discordius** [comment]
Do we have a setting to easily disable it?

**Comment by Discordius** [comment]
Also, we need to fix the thing where she single line comments no longer properly expand when clicked

**Comment by jpaddison3** [comment]
Is the problem where code blocks are rendered like the comment is drunk fixed?
image (15)

**Comment by Raemon** [comment]
I don't actually think it makes sense to make PRs like this. When something is gated it's usually because it's lacking some feature, and usually the creation of that feature is the correct moment to ungate it.

**Pull request closed without merging**
