### PR TITLE
Suggest Tags based on Pingbacks

### PR DESCRIPTION
**Pull request by Raemon**
This adds a resolverOnly field to posts, which currently:

1. Checks for pingbacks for that post
2. Checks for tags on those pingbacks
3. Returns those tags as "suggested tags" for the post.

Those tags are then show up instead of the core tags when you click "Add Tag" for that post. Over time I'd want to fine tune exactly how those posts are selected (potentially using other heuristics).

Issues with the current PR I could use help with:
- I couldn't figure out how to get the getWithLoader working for pingbacks
- I'm currently just passing the tags into TagSearchHit, which... magically works fine, but I'm sorta surprised, and guessing I should be doing something to properly match the types. (I can probably figure this one out more easily on my own, haven't actually tried to yet)

### CODE REVIEW

**Comment by jimrandomh** [comment]
I suspect this may have a significant performance impact on post-pages, especially for posts that have a lot of other posts linking to them. There are two ways to address this: either defer loading the suggested tags until after the Add Tag button is clicked, or optimize the resolver hard. The former seems probably better to me.

**Comment by Raemon** [comment]
This turned out to just not help that much (I tried using it locally to tag things and it didn't really help). So, closing it.

**Comment by darkruby501** [comment]
Oh yeah, this was an argument Ray and I had that I forget in the Argument Review. Initially, I thought performance would complicate it, then I was convinced that since all the relevant data was loaded already (but maybe it was only fake loaded?). So in the end I think I'm right that this wasn't a quick thing  (separate from its value).

**Comment by Raemon** [comment]
I'm fairly confident we could fix the performance, probably in about a day
(though defer to Jim). I just don't think the feature worked the way it was
intended, so optimizing it isn't worthwhile.

**Comment by darkruby501** [comment]
My argument wasn't that it couldn't be fixed, it was that the feature (even assuming it worked well) wasn't going to be completed and shipped by the end of that week and was less value than the other polish tasks.

**Pull request closed without merging**
