### PR TITLE
Fix modal autofocus

### PR DESCRIPTION
**Pull request by Raemon**
For the Edit Tags modal and the New Question modal, by default the modal was enforcing an auto-focus on the modal which was preventing some other features from working.

I'm not sure what purpose the autofocus is supposed to be serving, it's possible this should just be disabled all-around by default (currently modals default to 'steal focus')

### CODE REVIEW

**Comment by jimrandomh** [comment]
I'm confused. If you can focus outside a modal, then it's definitionally not a modal. Is this turning the New Questions modal into a non-modal popup? If so, what happens to its click-away behavior?

**Comment by jimrandomh** [comment]
Ok, it looks like what's happening here is that CkEditor and the add-tag dialog hit this open material UI bug: https://github.com/mui-org/material-ui/issues/15694 . This looks like the right workaround, but I'd leave a comment so we can take it out in case material-UI ever fixes the bug.

**Comment by jimrandomh** [comment]
It looks like there are a few other obscure places where we use `Dialog` which will also have the issue with not being able to use CkEditor links, most importantly `ModerationGuidelinesEditForm`, `NewShortformDialog` and `GroupFormDialog`. My inclination is to create a thin wrapper `LWDialog` which adds the `disableEnforceFocus` prop, and ban use of `Dialog` without the wrapper.

**Comment by Raemon** [comment]
I agree about making a LWDialog component but didn't have time today to delve into the details of that (it's not a huge project but would move this from a quick 5 minute project to a 30 minute one, and I wanna focus on tag stuff)

But I added a fix for the other dialogs you mentioned

**Pull request merged**
