### PR TITLE
Rearchitect ShowParentComment

### PR DESCRIPTION
**Pull request by jimrandomh**
Not tested yet.

### CODE REVIEW

**Comment by Raemon** [comment]
Note the merge conflicts

**Comment by Raemon** [comment]
This breaks some UI. Instead of:

image

You get:

image

**Comment by jimrandomh** [comment]
Good catch; fixed.

**Comment by Raemon** [comment]
Merge conflicts again tho

**Comment by jimrandomh** [comment]
I don't think merge conflicts are a good reason to assign back something that's unreviewed. You can still test, and it's not like merges themselves ever get reviewed anyways.

**Pull request merged**
