### PR TITLE
Tag pages have table of contents

### PR DESCRIPTION
**Pull request by jimrandomh**
Tag pages have tables of contents. Various changes to ToC code to make it able to handle things that aren't posts. Tag descriptions aren't usually long enough to need ToCs, but this provides a place to put the contributor-list, which will come in a future PR.

### CODE REVIEW

**Comment by Discordius** [comment]
A bunch of unused variables that we should remove. 

Code looks reasonable and straightforward. I haven't yet gotten around to reviewing whether we introduced any styling problems or other edge-cases.

**Comment by Discordius** [comment]
On the tag-page, we should increase the padding for the top of the ToC: 

image

I found that it looks pretty good with 12px padding at the top. The current thing is misaligned with the start of the text. 

Separately, we probably should make it so that the we somehow expand the post if you click on any navigation item in the ToC. Currently you can get links in the ToC to sections that are hidden, and when you click on them, nothing happens: 

image

**Comment by Discordius** [comment]
Those two do feel kind of blocking. Like, the lack of alignment does throw off my visual processing a bunch and feels important. I am less confident about not being able to navigate to hidden elements, but my guess is it's also pretty confusing.

**Comment by jimrandomh** [comment]
Discovered during testing: the layout breaks horribly on answer pages with ToCs (but not non-answer posts). Will fix before merge.

**Comment by jimrandomh** [comment]
Actually the layout brokenness is only on the other branch (with the contributors list), this one is fine.

**Review by Discordius — APPROVED** [review]

**Pull request merged**
